name: 'build'

on:
  push:
    branches: 
      - master
      - feature/*
      - hotfix/*
    tags:
      - linux-msft-wsl-*
  pull_request: {}
  workflow_call: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Kernel
        run: |
          sudo apt-get update -yqq
          sudo bash build-kernel
          cp linux-msft-wsl-*/arch/x86/boot/bzImage .
      - name: Upload bzImage
        uses: actions/upload-artifact@v3
        with:
          name: bzImage
          path: bzImage
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: bzImage
